openapi: 3.0.0   # Open api version

info:   # Set basic infomation
  title: Youtuber's-video-wordcloud
  version: "v0.1"
  contact:
    name: AInizer - Lee hoseop
  description: |
    Make a youtuber's video title word cloud...
    ---
      How to use:
      * First, get youtuber channel url using find_youtuber request body. (ex. AI network)
      * Second, copy youtuber chennel url (ex. /channel/UCnyBeZ5iEdlKrAcfNbZ-wog)
      * Last, paste url in make_wordcloud request body.

servers:   # Set your server endpoint
  - url: https://master-word-cloud-fpem123.endpoint.ainize.ai/

paths:
  /word-cloud/find_youtuber:
    post:
      requestBody:
        required: true
        description: This request can get a youtuer's channel url (but, it is some part, not full url).
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                youtuber:
                  type: string
      responses:   # Set response
        '200':
          description: "Successful Response"
          content:
            application/json:
              schema:
                type: object
        '400':
          description: "Bad Request Error"
        '404':
          description: "Target not found"
        '429':
          description: "Too many requests"
        '500':
          description: "Wrong request"
          
          
  /word-cloud/make_wordcloud:
    post:
      requestBody:
        required: true
        description: This request make a video title word cloud.
          And it need some time.
          Request exam /channel/UCnyBeZ5iEdlKrAcfNbZ-wog or /user/pewdiepie
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                youtuber:
                  type: string
      responses:   # Set response
        '200':
          description: "Successful Response"
          content:
            images/*:
              schema:
                type: string
                format: binary
        '400':
          description: "Bad Request Error"
        '429':
          description: "Too many requests"
        '500':
          description: "Wrong request"
